---
title: "Samples [Batch: MURGIGV01_20201118]"
author: "Belinda Cornes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning=FALSE)

library("kableExtra")
library("knitr")
options(stringsAsFactors = FALSE)
library(data.table) 
library(tidyr)     
library(mclust)     
library(rhdf5)      
library(optparse)
library(dplyr)
library(cluster)
library(readxl)
library(tibble)


filepathg = '/Users/corneb/Documents/MyJax/CS/Projects/Oconnor/Neogen/Jackson_Lab_Korstanje_MURGIGV01_20201118/'
filepaths = '/Users/corneb/Documents/MyJax/CS/Projects/Oconnor/genoprobs/3.batches/qced.samples/'
#filepathp = '/projects/compsci/corneb_cs/workflowr/Thaiss/Thaiss_workflowr_2/data/'

report_file <- dir(path = filepathg, pattern = "_FinalReport.zip$", full.names = TRUE)
sample_file <- dir(path = filepaths, pattern = "^DODB_*", full.names = TRUE)
#pheno_file <- dir(path = filepathp, pattern = "Uni_of_Penn_Thaiss_pheno.3.csv", full.names = TRUE)

report_file_hdr <- unlist(strsplit(report_file, split = "/"))
report_file_hdr <- report_file_hdr[length(report_file_hdr)]

header <- read.table(unz(report_file, sub(pattern = "zip$", replacement = "txt", report_file_hdr)), 
                      sep = "\t", skip = 1, nrows = 2)
report <- fread(paste("unzip -cq", report_file),
                 skip = 9, showProgress = TRUE, sep = "\t")
#samples <- fread(paste0("unzip -cq ",  sample_file))
colnames(report) <- gsub(" |-", "_", colnames(report))

geno <- report %>%
    select(Sample_ID, SNP_Name, Allele1___Forward, Allele2___Forward) %>%
    mutate(Sample_ID = factor(Sample_ID, levels = unique(report$Sample_ID))) %>%
    unite(genotype, c("Allele1___Forward", "Allele2___Forward"), sep = "") %>%
    spread(Sample_ID, genotype)
 
#pheno <- read.csv(pheno_file)
#pheno$indexp <- 1:nrow(pheno)
samples <- read.csv(sample_file)
samples$indexs <- 1:nrow(samples)
#samphen <- merge(samples,pheno, by.x=c("Unique.Sample.ID"), by.y=c("Mouse.ID"), all.x=T)
samphen <- samples[samples$Directory == "Jackson_Lab_Korstanje_MURGIGV01_20201118",]


genon <- geno[c(2:length(geno))]

library(tibble)

summaryInfo <- list()
for(i in (1:length(genon))){
#for(i in 100){
  tot <- as.data.frame(t(table(genon[,i])))
  tot <- t(tot[c(2:3)])
  tot <- data.frame(tot)
  names(tot) <- tot[1,]
  tot <- tot[-1,]
  names(tot)[1] <- c("Missing")
  rownames(tot) <- 1:nrow(tot)
  cols <- c(0,0,0,0,0,0,0,0,0,0,0,0,0)
  names(cols) <- c("Missing","AA","AC","AG","AT","CC","CG","GC","GG","TA","TC","TG","TT")
  totn <- add_column(tot, !!!cols[setdiff(names(cols), names(tot))])
  total <- data.frame(colSums(genon[i] != "--"))
  names(total) <- c("Total_Genotyped")
  sample <- data.frame(paste(names(genon[i])))
  names(sample) <- c("Neogen_Sample_ID")
  totall <- cbind(sample,totn,total)
  totall$Percent_Genotyped <- paste0(format(100*(round((total[1]/nrow(genon)), digits = 4)), nsmall = 2),"%")
  totall$MURGIGV01_SNP.Count <- as.numeric(as.character(totall$Missing)) + as.numeric(totall$Total_Genotyped)

  #sample Information
  totphensam <- merge(totall, samphen, by.x=c("Neogen_Sample_ID"), by.y=c("Original.Mouse.ID")) 
  #totphensam$Thaiss_ID <- ifelse((totphensam$Thaiss.ID == '995' | totphensam$Thaiss.ID == '996' | 
  #                              totphensam$Thaiss.ID == '997' | totphensam$Thaiss.ID == '998' | 
  #                              totphensam$Thaiss.ID == '999'), '--',totphensam$Thaiss.ID  )

  #totphensam$Time_min <- ifelse(totphensam$Time_.min. == 'NA' , '--',totphensam$Time_.min. )
  #totphensam$Distance_m <- ifelse(totphensam$Distance_.m. == 'NA' , '--',totphensam$Distance_.m. )
  #totphensam$Energy_J <- ifelse(totphensam$Energy_.J. == 'NA' , '--',totphensam$Energy_.J. )
    
  #finalsum <- cbind(totphensam[c(41,1)],
  #                 totphensam[c("Missing","AA","AC","AG","AT","CC","CG","GC","GG","TA","TC","TG","TT")],
  #                 totphensam[c(15,16,24:26,22,33:34,23,42:44,29:30,36)])

  finalsum <- totphensam

  names(finalsum)[22] <- c("Provided.Sex")
  #finalsum$Sex_Pheno <- replace(finalsum$Sex_Geno, finalsum$Sex_Pheno == '', '--')
  #finalsum$Sex_Geno <- replace(finalsum$Sex_Geno, finalsum$Sex_Geno == '', '--')
  summaryInfo[[i]] <- finalsum
}

summary <- do.call(rbind, summaryInfo)

summary$Provided.Sex <- replace(summary$Provided.Sex, summary$Provided.Sex == '', '--')
#summary$Sex_Geno <- replace(summary$Sex_Geno, summary$Sex_Geno == '', '--')
summary[is.na(summary)] <- '--'
#summary <- summary[order(summary$indexp),]
#names(summary)[21] <- c("DO.Generation")

which(summary$cr <.90)
#9 11 30 46 53 58 65 66 68 74

#substring(summary$Provided.Sex, 1, 1)
## [1] "h"
#substring(summary$Provided.Sex, 2)
## [1] "ello stackoverflow"

which(substring(summary$Provided.Sex, 1, 1) != summary$Inferred.Sex)
#2  7  9 58 65 66 74 92 93

control.mice <- c("B6 - 1614A", 
                "B6 - 1614", 
                "B6 - 1615A", 
                "B6 - 1615", 
                "B6 - 1616A", 
                "B6 - 1616", 
                "B6 - 1617", 
                "B6 - 1618A",
                "B6 - 1618C",
                "B6 - 1618A", 
                "B6 - 1618B", 
                "A-1620-20A", 
                "A-1620-20B", 
                "A-1620-20C", 
                "A-1620-20", 
                "A-1626-20D", 
                "A-1626-20")

#summary$DO.Generation <- ifelse(summary$Neogen_Sample_ID %in% control.mice, "--",summary$DO.Generation)
summary[summary$Neogen_Sample_ID %in% control.mice,]$DO.Generation <- '--'

```

### Genotype Summary by Sample
```{r plot table genotype summary}

rownames(summary) <- NULL

summary[c(1:17,31)] %>%
  kable(escape = F,align = c("ccccccccccccccccc"),linesep ="\\hline") %>%
  kable_styling("striped", full_width = T) %>%
  column_spec(3:15, width = "5cms") %>%
  row_spec(9,color= "white",background = "red") %>%
  row_spec(11,color= "white",background = "red") %>%
  row_spec(30,color= "white",background = "red") %>%
  row_spec(46,color= "white",background = "red") %>%
  row_spec(53,color= "white",background = "red") %>%
  row_spec(58,color= "white",background = "red") %>%
  row_spec(65,color= "white",background = "red") %>%
  row_spec(66,color= "white",background = "red") %>%
  row_spec(68,color= "white",background = "red") %>%
  row_spec(74,color= "white",background = "red") 

  #9 11 30 46 53 58 65 66 68 74

```

### Gender Summary by Sample
```{r plot table gender summary}

summary[c(1,22:24)] %>%
  kable(escape = F,align = c("cccc"),linesep ="\\hline") %>%
  kable_styling(full_width = F) %>%
  kable_styling("striped", full_width = F) %>%
  column_spec(1:4, width = "3cm") %>%
  row_spec(2 ,color= "white",background = "blue")  %>%
  row_spec(7 ,color= "white",background = "blue")  %>%
  row_spec(9 ,color= "white",background = "blue")  %>%
  row_spec(58 ,color= "white",background = "blue")  %>%
  row_spec(65 ,color= "white",background = "blue")  %>%
  row_spec(66 ,color= "white",background = "blue")  %>%
  row_spec(74 ,color= "white",background = "blue")  %>%
  row_spec(92 ,color= "white",background = "blue")  %>%
  row_spec(93 ,color= "white",background = "blue")  

#2  7  9 58 65 66 74 92 93

```

### Phenotype Summary by Sample
```{r plot table phenotype summary}

#summary[c(1:3,31,33,34,38)] %>%
#  kable(escape = F,align = c("ccccccccc"),linesep ="\\hline") %>%
#  kable_styling(full_width = F) %>%
#  kable_styling("striped", full_width = F) %>%
#  column_spec(1:7, width = "3cm") #%>%
  #row_spec(197 ,color= "white",background = "green")

```

no information about phenotypes


### All Problematic Samples
```{r plot table all problematic samples}

dis <- NULL
#dis$Original.Mouse.ID <- summary$Original.Mouse.ID
dis$Neogen_Sample_ID <- summary$Neogen_Sample_ID
#dis$Mouse.ID <- summary$Mouse.ID
#dis$no_pheno <- ifelse(summary$Max_IOP == '--', 'XX', '')
dis$low_call.rate <- ifelse(summary$cr <.90, 'XX', '')
dis$different_sex <- ifelse(substring(summary$Provided.Sex, 1, 1) != summary$Inferred.Sex, 'XX', '')

dis <- data.frame(dis)
disind <- subset(dis, dis$different_sex =="XX" | dis$low_call.rate == 'XX')

#disind[] %>% 
#   mutate(
#     possible_duplicate = ifelse(possible_duplicate == 'XX',
#                  cell_spec(possible_duplicate, color = 'orange',background = 'orange'),
#                  ''),
#     low_call.rate = ifelse(low_call.rate == 'XX',
#                  cell_spec(low_call.rate, color = 'red',background = 'red'),
#                  ''),
#     different_sex = ifelse(different_sex == 'XX',
#                  cell_spec(different_sex, color = 'blue',background = 'blue'),
#                  '')
#     ) %>%
#   kable(escape = F,align = c("cccc"),linesep ="\\hline") %>%
#   kable_styling("striped", full_width = F) %>%
#   column_spec(1:5, width = "3cm") 

disind[] %>% 
   mutate(
     #no_pheno = ifelse(no_pheno == 'XX',
     #             cell_spec(no_pheno, color = 'green',background = 'green'),
     #             ''),
     low_call.rate = ifelse(low_call.rate == 'XX',
                  cell_spec(low_call.rate, color = 'red',background = 'red'),
                  ''),
     different_sex = ifelse(different_sex == 'XX',
                  cell_spec(different_sex, color = 'blue',background = 'blue'),
                  ''),
     ) %>%
   kable(escape = F,align = c("ccc"),linesep ="\\hline") %>%
   kable_styling("striped", full_width = F) %>%
   column_spec(1:3, width = "3cm") 

```