---
title: "Step 2: SNP QC [Reinholdt Samples]"
author: "Belinda Cornes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

setwd("/Users/corneb/Documents/MyJax/CS/Projects/Korstanje-Oconnor/workflowr/Korstanje-OConnor_Workflow")

#libraries
library(broman)
library(qtl2)
library(qtlcharts)
library(ggplot2)
library(ggrepel)
#library(DOQTL)
library(mclust)
#source("code/reconst_utils.R")
library("kableExtra")
library("knitr")
library("fst")
```

### Loading Project
```{r loading project}
load("data/e_g_snpg_samqc_reinholt.RData")
gm <- get(load("data/gm_samqc_reinholt.RData"))

gm
```

### Marker Missing Data 
```{r Missing data in Markers and Genotype frequencies Markers, fig.height = 6, fig.width = 9.5, fig.align = "center"}

pmis_mar <- n_missing(gm, "marker", "proportion")*100
save(pmis_mar, file = "data/percent_missing_marker_reinholt.RData")

par(mar=c(5.1,0.6,0.6, 0.6))
hist(pmis_mar, breaks=seq(0, 100, length=201),
     main="", yaxt="n", ylab="", xlab="Percent missing genotypes")
rug(pmis_mar)

pdf(file = "output/Percent_missing_genotype_data_per_marker_reinholt.pdf")
par(mar=c(5.1,0.6,0.6, 0.6))
hist(pmis_mar, breaks=seq(0, 100, length=201),
     main="", yaxt="n", ylab="", xlab="Percent missing genotypes")
rug(pmis_mar)
dev.off()
```

```{r missing table, echo=FALSE}

pmis <- NULL
pmis$pmis_mar_5 <- sum(pmis_mar >= 5)
pmis$pmis_mar_10 <- sum(pmis_mar >= 10)
pmis$pmis_mar_15 <- sum(pmis_mar >= 15)
pmis$pmis_mar_25 <- sum(pmis_mar >= 25)
pmis$pmis_mar_50 <- sum(pmis_mar >= 50)
pmis$pmis_mar_75 <- sum(pmis_mar >= 75)
pmis$total_snps <- nrow(as.data.frame(pmis_mar))

pmis <- t(as.data.frame(pmis))
pmis <- as.data.frame(pmis)
pmis$count <- pmis$V1

pmis[c(2)] %>%
  kable(escape = F,align = c("ccccccccc"),linesep ="\\hline") %>%
  kable_styling(full_width = F) %>%
  kable_styling("striped", full_width = F)  %>%
  row_spec(7 ,bold=T,color= "white",background = "black")

```

### Marker Genotype Frequencies
```{r Genotype frequencies Markers, fig.height = 6, fig.width = 9.5, fig.align = "center"}

g <- do.call("cbind", gm$geno[1:19])
fg <- do.call("cbind", gm$founder_geno[1:19])
g <- g[,colSums(fg==0)==0]
fg <- fg[,colSums(fg==0)==0]
fgn <- colSums(fg==3)

gf_mar <- t(apply(g, 2, function(a) table(factor(a, 1:3))/sum(a != 0)))
gn_mar <- t(apply(g, 2, function(a) table(factor(a, 1:3))))

pdf(file = "output/genotype_frequency_marker_reinholt.pdf")
par(mfrow=c(2,2), mar=c(0.6, 0.6, 2.6, 0.6))
for(i in 1:4) {
  triplot(c("AA", "AB", "BB"), main=paste0("MAF = ", i, "/8"))
  z <- gf_mar[fgn==i,]
  z <- z[rowSums(is.na(z)) < 3,]
  tripoints(z, pch=21, bg="gray80", cex=0.6)
  tripoints(c((1-i/8)^2, 2*i/8*(1-i/8), (i/8)^2), pch=21, bg="violetred")
}
dev.off()

par(mfrow=c(2,2), mar=c(0.6, 0.6, 2.6, 0.6))
for(i in 1:4) {
  triplot(c("AA", "AB", "BB"), main=paste0("MAF = ", i, "/8"))
  z <- gf_mar[fgn==i,]
  z <- z[rowSums(is.na(z)) < 3,]
  tripoints(z, pch=21, bg="gray80", cex=0.6)
  tripoints(c((1-i/8)^2, 2*i/8*(1-i/8), (i/8)^2), pch=21, bg="violetred")
}

save(gf_mar, file = "data/genotype_freq_marker_reinholt.RData")

```

### Marker Genotype Errors
```{r Genotype errors Markers, fig.height = 6, fig.width = 9.5, fig.align = "center"}
errors_mar <- colSums(e>2)/n_typed(gm, "marker")*100

grayplot(pmis_mar, errors_mar,
         xlab="Proportion missing", ylab="Proportion genotyping errors")

pdf(file = "output/genotype_error_marker_reinholt.pdf")
grayplot(pmis_mar, errors_mar,
         xlab="Proportion missing", ylab="Proportion genotyping errors")
dev.off()

save(errors_mar, file = "data/genotype_errors_marker_reinholt.RData")

```

### Removing Markers
#### Missingness
```{r listing markers missing, echo=FALSE}

#Missingness

length(pmis_mar[pmis_mar >= 10])

high_miss <- find_markerpos(gm, names(pmis_mar[pmis_mar >= 10]))
high_miss$id <- rownames(high_miss)
high_miss_df <- as.data.frame(pmis_mar[pmis_mar >= 10])
high_miss_df$index = 1: nrow(high_miss_df)
high_miss_df$id <- rownames(high_miss_df)

high_miss_bad <- merge(high_miss,high_miss_df, by=c("id"),all=T)
names(high_miss_bad)[5] <- c("high_miss")
names(high_miss_bad)[1] <- c("marker")
high_miss_bad <- high_miss_bad[order(high_miss_bad$index),]
```

#### Monomorphic/Low Frequency markers
```{r listing markers Monomorphic or Low Frequency markers, echo=FALSE}

#Monomorphic/Low Frequency markers

low_freq_df <- as.data.frame(gf_mar)
low_freq_df$count <- rowSums(low_freq_df <= 0.01)
low_freq_df[is.na(low_freq_df)] <- ''
low_freq_df <- low_freq_df[low_freq_df$count == 2,]
low_freq_df$id <- rownames(low_freq_df)
low_freq_df$index = 1: nrow(low_freq_df)
low_freq <- find_markerpos(gm, rownames(low_freq_df))
low_freq$id <- rownames(low_freq)

nrow(low_freq)

low_freq_bad <- merge(low_freq,low_freq_df, by=c("id"),all=T)
names(low_freq_bad)[5] <- c("AA_freq")
names(low_freq_bad)[6] <- c("AB_freq")
names(low_freq_bad)[7] <- c("BB_freq")
names(low_freq_bad)[1] <- c("marker")
low_freq_bad <- low_freq_bad[order(low_freq_bad$index),]

```

#### Genotyping Error
```{r listing markers Genotyping Error, echo=FALSE}

##Genotyping Error

length(errors_mar[errors_mar > 5])

error_markers_names <- names(errors_mar[errors_mar > 5])
error_markers_names <- error_markers_names[complete.cases(error_markers_names)]

error_markers <- find_markerpos(gm, error_markers_names)
error_markers$id <- rownames(error_markers)
#rne <- rownames(as.data.frame(errors_mar))
error_mars_df <- as.data.frame(errors_mar[errors_mar > 5])
error_mars_df <- error_mars_df[complete.cases(error_mars_df$"errors_mar[errors_mar > 5]"),]
error_mars_df <- as.data.frame(error_mars_df)
#error_mars_df$id = rownames(error_mars_df)
error_mars_df$index = 1: nrow(error_mars_df)

#error_markers_bad <- merge(error_markers,error_mars_df, by=c("id"),all=T)
error_markers_bad <- cbind(error_markers,error_mars_df)
names(error_markers_bad)[5] <- c("error_mars")
names(error_markers_bad)[4] <- c("marker")
error_markers_bad <- error_markers_bad[order(error_markers_bad$index),]

```

#### Total
```{r listing markers total, echo=FALSE}

### merge all

bad_markers <- rbind(high_miss_bad[c("marker","chr","gmap","pmap")], low_freq_bad[c("marker","chr","gmap","pmap")], error_markers_bad[c("marker","chr","gmap","pmap")])
#nrow(bad_markers)

duplicate <- bad_markers[duplicated(bad_markers),]

bad_markers <- bad_markers[!duplicated(bad_markers),]
nrow(bad_markers)

save(bad_markers, file = "data/bad_markers_all_reinholt.RData")

```
### Array Intensities


```{r Removing markers }

#missing in at least 10% of the samples


gm_allqc2 <- drop_markers(gm_samqc, bad_markers$marker)
gm_allqc <- drop_nullmarkers(gm_allqc2)


gm_allqc

save(gm_allqc, file = "data/gm_allqc_reinholt.RData")

```
