---
title: "Korstanje-OConnor Workflow"
author: "Belinda Cornes"
date: "`r Sys.Date()`"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: true
editor_options:
  chunk_output_type: console
---

### Project At A Glance [Total Samples: 570 (not including redone samples)]
* Samples: Jackson_Lab_Korstanje_MURGIGV01_20201111
	+ [Total Samples: 192](0.1_samples_batch_20201111.html)
* Samples: Jackson_Lab_Korstanje_MURGIGV01_20201118
	+ [Total Samples: 96](0.1_samples_batch_20201118.html)
* Samples: Jackson_Lab_Korstanje_MURGIGV01_20210211
	+ [Total Samples: 282](0.1_samples_batch_20210211.html)
* Redone Samples: Jackson_Lab_Korstanje_MURGIGV01_20210604 
	+ [Total Samples: 24](0.1_samples_batch_20210604.html)
* Redone Samples: Jackson_Lab_Korstanje_MURGIGV01_20210701 
	+ [Total Samples: 19](0.1_samples_batch_20210701.html)


### Haplotype Phasing
* 2 batches
	+ [Figures](0.2_haplotype_comparison_bqc.html)
	+ [Concordance](0.3_concordance_random_samples_bqc.html)
* 3 batches
	+ [Figures](0.2_haplotype_comparison_bqc_3batches.html)
	+ Concordance
* redone
	+ [Figures](0.2_haplotype_comparison_bqc_redone.html)
	+ Concordance


### 1. Phenotype QC
* Phenotypes
	+ no phenotypes


### 2. Genotype QC
* Step 1: Sample QC 
	+ 2 batches
		- [Without Controls](2.1_sample_bqc.html)
		- [With Controls](2.1_sample_bqc_wcont.html)
	+ 3 batches
		- [Without Controls](2.1_sample_bqc_3batches.html)
		- [With Controls](2.1_sample_bqc_wcont_3batches.html)
	+ redone
		- [With Controls](2.1_sample_bqc_wcont_redone.html)
* Step 2: SNP QC (Monomorphic, Genotype Error & Missing Data)
	+ 2 batches
		- [Without Controls](2.2.1_snp_qc.html)
		- [With Controls](2.2.1_snp_qc_wcont.html)
	+ 3 batches
		- [Without Controls](2.2.1_snp_qc_3batches.html)
		- [With Controls](2.2.1_snp_qc_wcont_3batches.html)
	+ redone
		- [With Controls](2.2.1_snp_qc_wcont_redone.html)
* Step 3: Effect of Data Cleaning
* Step 4: Preparing Files for QTL Analysis


### 3. QTL Analysis
* Step 1a: DO Report
* Step 1b: Recombination Block Size & Founder Proportions
* Step 2: GCTA Heritability
	+ no phenotypes for GCTA analysis
* Step 3: QTL Mapping (`R/qtl2`)
	+ no phenotypes for `R/qtl2` analysis
* Step 4: QTL Permutation (`R/qtl2`)
	+ no phenotypes for `R/qtl2` analysis
* Step 5: QTL Best Linear Unbiased Prediction (BLUP) (`R/qtl2`)
	+ no phenotypes for `R/qtl2` analysis
* Step 6: Results from `R/qtl2` analysis
	+ no phenotypes for `R/qtl2` analysis
